//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// HSglTFImporter.rc で使用
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_CLASS_NAME2                 6
#define IDD_PANEL                       101
#define IDD_EXPORT_DIALOG               102
#define IDD_GLTFX_DLG                   102
#define IDD_PROGRESS_DLG                104
#define IDD_TOOL_DLG                    106
#define IDD_DIALOG1                     108
#define IDD_NODEEXTENSION_DLG           111
#define IDC_CLOSEBUTTON                 1000
#define IDC_MATCHANIM_CHK               1001
#define IDC_ANIM_CHK                    1002
#define IDC_FLIPNRM_GRN_CHK             1003
#define IDC_FLIPNRM_RED_CHK             1004
#define IDC_COMPOSITE_CHK               1006
#define IDC_MTL_COMBO                   1007
#define IDC_EDIT_SCALE                  1008
#define IDC_SPIN_SCALE                  1009
#define IDC_EDIT_ANIMCH                 1010
#define IDC_SPIN_ANIMCH                 1011
#define IDC_MTL_RADIO1                  1012
#define IDC_MTL_RADIO2                  1013
#define IDC_MTL_RADIO3                  1014
#define IDC_MTL_RADIO4                  1015
#define IDC_MTL_RADIO5                  1016
#define IDC_MTL_RADIO6                  1017
#define IDC_MTL_RADIO7                  1018
#define IDC_MTL_RADIO8                  1019
#define IDC_MTL_RADIO9                  1020
#define IDC_MTL_RADIO10                 1021
#define IDC_MTL_RADIO11                 1022
#define IDC_EDIT_SCNCH                  1028
#define IDC_SPIN_SCNCH                  1029
#define IDC_UNIQUETEX_CHK               1030
#define IDC_VERTCOLOR_CHK               1031
#define IDC_NAMEOBJ_CHK                 1032
#define IDC_HIDEDMY_CHK                 1033
#define IDC_CLRCORRECT_CHK              1034
#define IDC_GAMMA_CHK                   1035
#define IDC_SCRIPT_CHK                  1036
#define IDC_USEOSL_CHK                  1037
#define IDC_INSTANCE_CHK                1038
#define IDC_ENABLEBKCOL_CHK             1039
#define IDC_SCRIPTSTR                   1040
#define IDC_SETFILE_BTN                 1041
#define IDC_IMAGEFILESTR                1042
#define IDC_LICENSE_BTN                 1043
#define IDC_RADIO1                      1044
#define IDC_RADIO2                      1045
#define IDC_RADIO3                      1046
#define IDC_SETBMP_BTN                  1047
#define IDC_ANIM_STATIC                 1048
#define IDC_CUSTATTR_CHK                1049
#define IDC_LICENSE_STATIC              1050
#define IDC_USERPROP_CHK                1050
#define IDC_LICENSE_EDIT                1051
#define IDC_SCLINTS_CHK                 1052
#define IDC_ATCATTR_BTN                 1053
#define IDC_SCN_BTN1                    1054
#define IDC_SCN_BTN2                    1055
#define IDC_SCN_BTN3                    1056
#define IDC_ROT_COMBO                   1057
#define IDC_ROTCTL_STATIC               1059
#define IDC_LOG_CHK                     1060
#define IDC_SEL_CHK                     1061
#define IDC_SELECT_CHK                  1062
#define IDC_FLAT_HIR_CHK                1063
#define IDC_HOV_CHK                     1064
#define IDC_VISIBLE_CHK                 1065
#define IDC_HOVER_CHK                   1066
#define IDC_NODEATTR_BTN                1067
#define IDC_DELATTR_BTN                 1068
#define IDC_NODEINDEX_BTN               1069
#define IDC_REMOVE_SELECTED_BTN         1070
#define IDC_VIS_CHK                     1071
#define IDC_APPLYSCL_CHK                1072
#define IDC_PROGRESS1                   1073
#define IDC_GLTFX_STATIC                1074
#define IDC_CM_CHECK                    1076
#define IDC_VIS_CHECK                   1077
#define IDC_NODEINDEX_LIST              1078
#define IDC_SEL_CHECK                   1080
#define IDC_BUTTON1                     1081
#define IDC_SETVAL_BUTTON               1081
#define IDC_HOV_CHECK                   1082
#define IDC_BUTTON2                     1084
#define IDC_ADD_BUTTON                  1085
#define IDC_NODE_COUNT                  1120
#define IDC_MTL_COUNT                   1121
#define IDC_TEX_COUNT                   1122
#define IDC_ANIM_COUNT                  1123
#define IDC_SKIN_COUNT                  1124
#define IDC_MORPH_COUNT                 1125
#define IDC_PHYSIC_COUNT                1125
#define IDC_NODE_STATE                  1130
#define IDC_MTL_STATE                   1131
#define IDC_TEX_STATE                   1132
#define IDC_ANIM_STATE                  1133
#define IDC_SKIN_STATE                  1134
#define IDC_PHYSIC_STATE                1135
#define IDC_NODE_PROGRESS               1140
#define IDC_MTL_PROGRESS                1141
#define IDC_TEX_PROGRESS                1142
#define IDC_ANIM_PROGRESS               1143
#define IDC_SKIN_PROGRESS               1144
#define IDC_MORPH_PROGRESS              1145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
